remote_theme: just-the-docs/just-the-docs
color_scheme: dark
collections:
  projects:
    permalink: "/:collection/:path/"
    output: true

just_the_docs
  collections:
    projects:
      name: Projects